/**
 * Created by zhanghua on 2017/8/16.
 */
export default{
        info:{
            year:2017,
            month:7
        },
        data: [{
            "title":"税前收入11",
            "maney":"1900",
            "data":[
                {
                    "name":"请假扣款1",
                    "maney":"2200.15"
                },
                {
                    "name":"请假扣款2",
                    "maney":"3200.15"
                },
                {
                    "name":"请假扣款3",
                    "maney":"14200.15"
                }
            ]
        },{
            "title":"税前收入11",
            "maney":"1900",
            "data":[
                {
                    "name":"请假扣款1",
                    "maney":"2200.15"
                },
                {
                    "name":"请假扣款2",
                    "maney":"3200.15"
                },
                {
                    "name":"请假扣款3",
                    "maney":"14200.15"
                }
            ]
        },{
            "title":"税前收入11",
            "maney":"1900",
            "data":[
                {
                    "name":"请假扣款1",
                    "maney":"2200.15"
                },
                {
                    "name":"请假扣款2",
                    "maney":"3200.15"
                },
                {
                    "name":"请假扣款3",
                    "maney":"14200.15"
                }
            ]
        },
        {
            "title":"税前收入22",
            "maney":"2300",
            "data":[
                {
                    "name":"请假扣款55",
                    "maney":"5200.15"
                }
            ]
        },
        {
            "title":"税前收入22",
            "maney":"2300",
            "data":[]
        }]
}



