/**
 * Created by tianxfc on 2017/10/11.
 */
export default {
    resdata: {
        "statusCode": 200,
        "message": "操作成功",
        "data": {
            "total_name": "总计",
            "sum_xiamen": 95,
            "sum_qingdao": 0,
            "sum_other": 47,
            "sum_total": 142,
            "sum_shenzhen": 0,
            "sum_guangzhou": 0,
            "sum_tianjin": 0,
            "sum_shanghai": 0,
            "sum_fuzhou": 0,
            "data": [{
                    "total": "合计",
                    "sum_row": 7,
                    "plate_name": "生化板块",
                    "plate_id": "100113100000000014XC",
                    "sum_shenzhen": 0,
                    "sum_guangzhou": 0,
                    "sum_xiamen": 0,
                    "sum_qingdao": 0,
                    "sum_other": 0,
                    "sum_tianjin": 0,
                    "sum_shanghai": 0,
                    "sum_fuzhou": 0,
                    "sum_total": 0,
                    "plate_sun": [{
                        "org_plate_id": "100113100000000014XC",
                        "sub": "小计",
                        "sum_total": 0,
                        "sum_shenzhen": 0,
                        "sum_guangzhou": 0,
                        "org_plate_name": "-",
                        "sum_xiamen": 0,
                        "sum_qingdao": 0,
                        "sum_other": 0,
                        "sum_tianjin": 0,
                        "sum_shanghai": 0,
                        "sum_row": 6,
                        "sum_fuzhou": 0,
                        "org_sun_item": [{
                                "org_name": "黑龙江金象生化有限责任公司",
                                "pk_org": "00011310000000001M81",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            },
                            {
                                "org_name": "富锦生化",
                                "pk_org": "00011310000000001MBK",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            },
                            {
                                "org_name": "北安生化",
                                "pk_org": "00011310000000001MBH",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            },
                            {
                                "org_name": "哈尔滨生化",
                                "pk_org": "00011310000000001MBE",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            },
                            {
                                "org_name": "绥化生化",
                                "pk_org": "00011310000000001MBN",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            }
                        ]
                    }]
                },
                {
                    "total": "合计",
                    "sum_row": 3,
                    "sum_shenzhen": 0,
                    "sum_guangzhou": 0,
                    "sum_xiamen": 95,
                    "sum_qingdao": 0,
                    "sum_other": 17,
                    "sum_tianjin": 0,
                    "sum_shanghai": 0,
                    "sum_row": 3,
                    "sum_fuzhou": 0,
                    "plate_sun": [{
                        "org_plate_id": "100113100000000014XO",
                        "sub": "小计",
                        "sum_total": 112,
                        "sum_shenzhen": 0,
                        "sum_guangzhou": 0,
                        "org_plate_name": "集团本部",
                        "sum_xiamen": 95,
                        "sum_qingdao": 0,
                        "sum_other": 17,
                        "sum_tianjin": 0,
                        "sum_shanghai": 0,
                        "sum_row": 2,
                        "sum_fuzhou": 0,
                        "org_sun_item": [{
                            "org_name": "象屿集团本部",
                            "pk_org": "00011310000000001M7N",
                            "totalcnt": 112,
                            "fuzhou": 0,
                            "guangzhou": 0,
                            "xiamen": 95,
                            "othercnt": 17,
                            "shenzhen": 0,
                            "shanghai": 0,
                            "qingdao": 0
                        }]
                    }],
                    "plate_name": "集团",
                    "plate_id": "1001AA100000000003ZF"
                },
                {
                    "total": "合计",
                    "sum_row": 92,
                    "sum_shenzhen": 0,
                    "sum_guangzhou": 0,
                    "sum_xiamen": 95,
                    "sum_qingdao": 0,
                    "sum_other": 17,
                    "sum_tianjin": 0,
                    "sum_shanghai": 0,
                    "sum_fuzhou": 0,
                    "plate_sun": [{
                            "org_plate_id": "100113100000000014X3",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "境外板块",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 6,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                    "org_name": "股份境外",
                                    "pk_org": "00011310000000001M8V",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿美国",
                                    "pk_org": "00011310000000001MDP",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿迪拜",
                                    "pk_org": "00011310000000001MDU",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿新加坡",
                                    "pk_org": "00011310000000001MDM",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "香港拓威",
                                    "pk_org": "00011310000000001MDJ",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                }
                            ]
                        },
                        {
                            "org_plate_id": "100113100000000014X5",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "合资板块",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 19,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                    "org_name": "环资-大丰新安德",
                                    "pk_org": "00011310000000001MET",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "南通象屿",
                                    "pk_org": "00011310000000001MFA",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "兴泓特种",
                                    "pk_org": "00011310000000001MEF",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿张家港",
                                    "pk_org": "00011310000000001MDX",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "大连港象屿",
                                    "pk_org": "00011310000000001MFJ",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "股份合资",
                                    "pk_org": "00011310000000001M8Y",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "环资股份",
                                    "pk_org": "00011310000000001MEQ",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿同道",
                                    "pk_org": "00011310000000001MFG",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "徐州象屿",
                                    "pk_org": "00011310000000001MF5",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "环资-镇江新安德",
                                    "pk_org": "00011310000000001MEX",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "兴泓超细",
                                    "pk_org": "00011310000000001MEI",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿兴泓",
                                    "pk_org": "00011310000000001MEC",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "天津象屿立业",
                                    "pk_org": "00011310000000001ME9",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "江苏象屿国贸",
                                    "pk_org": "00011310000000001ME1",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象道物流",
                                    "pk_org": "00011310000000001MFD",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "唐山象屿",
                                    "pk_org": "00011310000000001ME6",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿盛洲",
                                    "pk_org": "00011310000000001MF0",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "兴泓新材料",
                                    "pk_org": "00011310000000001MEN",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                }
                            ]
                        },
                        {
                            "org_plate_id": "100113100000000014X6",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "农产板块",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 13,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                    "org_name": "富锦金谷",
                                    "pk_org": "00011310000000001MGU",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "讷河农产",
                                    "pk_org": "00011310000000001MGO",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "绥化象屿",
                                    "pk_org": "00011310000000001MGF",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "依安象屿",
                                    "pk_org": "00011310000000001MG9",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "五大连池农产",
                                    "pk_org": "00011310000000001MGC",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "嫩江农产",
                                    "pk_org": "00011310000000001MGI",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "股份农产",
                                    "pk_org": "00011310000000001M91",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "农产集团",
                                    "pk_org": "00011310000000001MG6",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "北安金谷",
                                    "pk_org": "00011310000000001MGZ",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "北安象屿",
                                    "pk_org": "00011310000000001MGL",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "绥化金谷",
                                    "pk_org": "00011310000000001MH2",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "大连农产",
                                    "pk_org": "00011310000000001MGR",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                }
                            ]
                        },
                        {
                            "org_plate_id": "100113100000000014X7",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "园区板块",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 4,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                    "org_name": "股份园区",
                                    "pk_org": "00011310000000001M94",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "园区中心",
                                    "pk_org": "00011310000000001MH5",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "五金物流",
                                    "pk_org": "00011310000000001MH8",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                }
                            ]
                        },
                        {
                            "org_plate_id": "100113100000000014X8",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "配送板块",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 6,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                    "org_name": "东南物流港",
                                    "pk_org": "00011310000000001MHN",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "象屿商贸",
                                    "pk_org": "00011310000000001MHF",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "泉州园区",
                                    "pk_org": "00011310000000001MHK",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "配送中心",
                                    "pk_org": "00011310000000001MHC",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                },
                                {
                                    "org_name": "股份配送",
                                    "pk_org": "00011310000000001M99",
                                    "totalcnt": 0,
                                    "fuzhou": 0,
                                    "guangzhou": 0,
                                    "xiamen": 0,
                                    "othercnt": 0,
                                    "shenzhen": 0,
                                    "shanghai": 0,
                                    "qingdao": 0
                                }
                            ]
                        },
                        {
                            "org_plate_id": "100113100000000014X9",
                            "sub": "小计",
                            "sum_total": 0,
                            "sum_shenzhen": 0,
                            "sum_guangzhou": 0,
                            "org_plate_name": "集团投资-股份管理",
                            "sum_xiamen": 0,
                            "sum_qingdao": 0,
                            "sum_other": 0,
                            "sum_tianjin": 0,
                            "sum_shanghai": 0,
                            "sum_row": 3,
                            "sum_fuzhou": 0,
                            "org_sun_item": [{
                                "org_name": "集团投资-股份管理",
                                "pk_org": "00011310000000001M9F",
                                "totalcnt": 0,
                                "fuzhou": 0,
                                "guangzhou": 0,
                                "xiamen": 0,
                                "othercnt": 0,
                                "shenzhen": 0,
                                "shanghai": 0,
                                "qingdao": 0
                            }]
                        }
                    ]
                }
            ]
        }
    }
}